name: Build Electron App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04.1, windows-latest] # Use the specific Ubuntu version once it is supported.

    steps:
      # Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # Install dependencies on Ubuntu
      - name: Install Ubuntu Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang libdbus-1-dev libgtk-3-dev \
              libnotify-dev libasound2-dev libcap-dev \
              libcups2-dev libxtst-dev libxss1 libnss3-dev \
              gcc-multilib g++-multilib curl gperf bison \
              python3-dbusmock openjdk-8-jre

      # Change directory to the 'desktop' folder
      - name: Change to Desktop Directory
        run: cd desktop

      # Install npm dependencies
      - name: Install Dependencies
        run: npm install
        working-directory: desktop

      # Build the Electron app
      - name: Build App
        run: npm run build
        working-directory: desktop

      # Package the Electron app for the specific OS
      - name: Package App
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-24.04.1" ]; then
            npm run dist:linux
          elif [ "${{ matrix.os }}" == "windows-latest" ]; then
            npm run dist:win
          fi
        working-directory: desktop

      # Save the built artifacts
      - name: Save Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: electron-app-${{ matrix.os }}
          path: desktop/dist/*
